'use strict';

angular.module('bahmni.common.obs')
    .directive('showObservation', ['ngDialog', function (ngDialog) {
        var controller = function ($scope, $rootScope, $filter) {
            $scope.toggle = function (observation) {
                observation.showDetails = !observation.showDetails;
            };
            $scope.print = $rootScope.isBeingPrinted || false;

            $scope.dateString = function (observation) {
                var filterName;
                if ($scope.showDate && $scope.showTime) {
                    filterName = 'bahmniDateTime';
                } else if (!$scope.showDate && ($scope.showTime || $scope.showTime === undefined)) {
                    filterName = 'bahmniTime';
                } else {
                    return null;
                }
                return $filter(filterName)(observation.observationDateTime);
            };
            $scope.openVideoInPopup = function (observation) {
                ngDialog.open({
                    template: "../common/obs/views/showVideo.html",
                    closeByDocument: false,
                    className: 'ngdialog-theme-default',
                    showClose: true,
                    data: {
                        observation: observation
                    }
                });
            };


            $scope.checkMultipleSelectionElement = function (observation) {
                debugger;
                if(observation.groupMembers && observation.groupMembers.length <= 0) {
                    if(observation.concept.name == 'HIVTC, TB Treatment Outcome' || observation.concept.name == 'HIVTC, TB Treatment Outcome') {
                        return false;
                    }
                    else return true;
                }
                else {
                      return true;
                }
            };

            //$scope.conceptDictionary = ["PNC","Date of maternal death","Cause of maternal death","Cause of neonatal death","Remarks","Gravida","Blood transfusion quantity","ANC","Vitals","Pulse"];
            // $scope.conceptDictionary = [
            //     "Chief Complaints",
            //     "Chief Complaint",
            //     "Pulse",
            //     "General Examination",
            //     "Anemia",
            //     "Client History",
            //     "Blood Pressure",
            //     "Systolic",
            //     "Diastolic",
            //     "BMI",
            //     "Abnormal sound in Heart",
            //     "Abnormal sound in  Lungs",
            //     "Mother Health",
            //     "Any Congenital Anomaly",
            //     "Difficulty in Feeding",
            //     "Notes",
            //     "Referred",
            //     "Yellow Skin",
            //     "Temperature 99.5 Degree F or More",
            //     "No Movement at all",
            //     "Cyanosis",
            //     "Any oral Issues",
            //     "History of Convulsion",
            //     "Is the baby breast Feeding",
            //     "Final Classification",
            //     "Severe Bleeding /Any Surgical Condition for Which Hospital Admission Needed",
            //     "Is the Child Able to Attach",
            //     "More Areola Above Than Below the Mouth",
            //     "Mouth Wide Open",
            //     "Child Chin Touches Breast",
            //     "Lower Lip Turned Outward",
            //     "RR",
            //     "Any problem in Feeding",
            //     "Any Other Food or Liquid Except Breast Feeding",
            //     "Next Vaccination Date",
            //     "Look for Severe Chest Indrawing",
            //     "Is the child Sucking Effectively",
            //     "Not Being Able to Feed",
            //     "Whole Body is Hold Properly",
            //     "Mouth of the Infant is Towards Mothers Breast",
            //     "Infant is Attached with Mothers Body",
            //     "Head and Body Straight",
            //     "Next Visit Date",
            //     "Umbilicus",
            //     "Weight According to Age",
            //     "Position",
            //     "Birth Weight <1500gm",
            //     "Lethargic/ Unconscious",
            //     "Look and Feel for Bulging Fontanelle",
            //     "History of Severe Bleeding",
            //     "Baby Breast Feed Attachment",
            //     "Temperature Data",
            //     "Temperature Abnormal",
            //     "Yellow Palm of the Hand",
            //     "Temperature 95.5 degree F or Less",
            //     "Yellow Sole of the Foot",
            //     "Check the Movement",
            //     "Child Convulsion",
            //     "No Movement",
            //     "Restless or Irritable",
            //     "No movement When Stimulation Given",
            //     "Issues",
            //     "Treatment given",
            //     "Moves Only When Stimulation Given",
            //     "Yellow Eyes",
            //     "Apnea During Sleeping for 20 Sec or More",
            //     "IMCI (age below 2 months)",
            //     "Does the child has any of this very severe disease sign?",
            //     "Does the child has any of this bacterial infection & severe disease sign?",
            //     "Does the child has any of this jaundice sign?",
            //     "Does the child has any of this dehydration sign?",
            //     "Feeding Problem/Low Weight",
            //     "Assess Breast Feeding",
            //     "Baby Position While Breast Feeding",
            //     "Immunization:",
            //     "MUAC (mm)",
            //     "Counselling on Exclusive Breastfeeding",
            //     "What Do You Use to Feed the Baby",
            //     "How Many Times in Last 24 Hours",
            //     "Able to Drink Properly (offer the child some fluid)",
            //     "Is There Ear Pain",
            //     "Chest Indrawing",
            //     "Height (Inch)",
            //     "Counselling on Complementary Feeding",
            //     "Pus Draining from the Ear",
            //     "Edema",
            //     "Severe Complications",
            //     "Fast Breathing",
            //     "Weight (kg)",
            //     "Bacterial Cause of Fever",
            //     "Duration (Days)",
            //     "Plasmodium Falciparum",
            //     "Provide a Nutrition Packet. Can S/he Finish It?",
            //     "Treatment Related Complication",
            //     "Malaria RDT",
            //     "Plasmodium Vivax",
            //     "Z Score",
            //     "Stridor",
            //     "Does the Baby Take Any Other Food or Fluids",
            //     "How Many Times Per Day",
            //     "Immunization Status",
            //     "Pinch the Skin of Abdomen, Does it Go Back",
            //     "During Illness, Baby Feeding Change",
            //     "Is There Ear Discharge",
            //     "Chest Indrawing in Case of Pneumonia?",
            //     "Decide Malaria Risk",
            //     "How Large are Serving (ml)",
            //     "Tender Swelling Behind the Ear",
            //     "Wheeze",
            //     "Fever Present for More than 7 Days",
            //     "Malaria Test Result",
            //     "Signs of Measles(Rash, Cough, Runny Nose, Red Eyes)",
            //     "Blood in Stool",
            //     "How Does the Baby Eat",
            //     "Ear Discharge Duration",
            //     "Breastfeed",
            //     "General Danger Signs",
            //     "Sunken Eyes",
            //     "Stiff Neck",
            //     "Runny Nose",
            //     "IYCF Counselling to Mother",
            //     "Breath Counts in 1 Minute",
            //     "Measles within last 3 months",
            //     "Do You Breastfeed During Night",
            //     "Palmar Pallor",
            //     "IMCI (age 2 months to 5 years)",
            //     "COUGH/ DIFFICULT BREATHING",
            //     "DIARRHEA",
            //     "Does The Child Have Fever",
            //     "EAR PROBLEM",
            //     "MALNUTRITION",
            //     "Immunization & Counselling",
            //     "Feeding",
            //     "Calcium Tablets Given",
            //     "TD History",
            //     "Danger signs of pregnancy",
            //     "IFA tablets Given",
            //     "Fetal Movement",
            //     "Fetal Presentation",
            //     "Counseling During ANC Visit",
            //     "Risk level of pregnant women",
            //     "Urine Sugar",
            //     "Blood Sugar",
            //     "Albumin",
            //     "HBsAg",
            //     "Anemia/ Hemoglobin",
            //     "TPHA",
            //     "USG Findings",
            //     "Uterine Height",
            //     "Fetal Heart Beats",
            //     "ANC visit number",
            //     "Risk Evaluation Score for pregnant women",
            //     "Date of Next ANC Visit",
            //     "Antenatal Care",
            //     "Lab Diagnosis/ Investigation",
            //     "Does she have history previous pregnancies",
            //     "Number of Pregnancies",
            //     "Number of living children",
            //     "Number of still birth",
            //     "Number of miscarriage",
            //     "Number of abortions",
            //     "Age of Last Child",
            //     "Mode of Delivery of Last child",
            //     "History of Ectopic Pregnancy_Obs",
            //     "History of Multiple Pregnancy",
            //     "History of Obstructed/Prolonged Labor",
            //     "Obstetric History",
            //     "Previous Pregnancy History",
            //     "New Born Baby Care",
            //     "Newborn Care Counselling on",
            //     "Respiratory Rate",
            //     "Newborn Examination",
            //     "Counselling",
            //     "Postnatal Care",
            //     "PNC visit number",
            //     "Breast Examination",
            //     "Uterine Height Measured",
            //     "Vaginal Discharge Happened",
            //     "Cervical wound/Cut",
            //     "Tear of Perineum",
            //     "Wound of C-section",
            //     "Danger signs of Post-delivery",
            //     "Post partium vitamin provided within 2 weeks",
            //     "Newborn Weight (Kg)",
            //     "Newborn Length (cm)",
            //     "Umbilical Cord Examined",
            //     "Temperature",
            //     "Rash",
            //     "Jaundice present",
            //     "Abnormality in Heart",
            //     "Abnormality in Lungs",
            //     "Newborn Conjunctivitis",
            //     "Injuries during birth",
            //     "Have Congenital Anomaly",
            //     "Continuing Exclusive Breast Feeding",
            //     "Vaccinated",
            //     "Vitamin K Given",
            //     "Any other complication",
            //     "Date of Next PNC Visit",
            //     "Mother's Examination",
            //     "Newborn's Examination",
            //     "Post Abortion Care",
            //     "Per Vaginal Findings",
            //     "Bi- Manual",
            //     "Tenderness",
            //     "Uterus Palpable",
            //     "Cervix",
            //     "Cervix Friability Test",
            //     "Adnexa",
            //     "PAFP method",
            //     "STI and RTI",
            //     "Physical Examination",
            //     "Per Abdominal examination",
            //     "Per Genital Examination",
            //     "Temperature> 38 degree C",
            //     "Curd like Discharge from Vagina",
            //     "Cervical Motion Tenderness (CMT)",
            //     "Fornix",
            //     "Redness, Swelling and Discharge of Eye (Newborn)",
            //     "VDS: Vaginitis",
            //     "VDS: Cervictis",
            //     "Pelvic Inflammatory Disease(LAP/PID)",
            //     "Genital Ulcer (GU)",
            //     "Ureteral Discharge or Sweollen Testes (UD/SS)",
            //     "Inguinal Bubo (IB)",
            //     "4C Yes",
            //     "Cervical Cancer",
            //     "Examination of External Genitalia",
            //     "Per Vaginal Examination",
            //     "Lower Abdominal pain",
            //     "Lump in Abdomen",
            //     "Swelling of Inguinal Glands",
            //     "Genital Ulcers",
            //     "Card like discharge from Patient's vagina",
            //     "Swelling/Inflammation/Discharge Around Anus",
            //     "Yellowish Pus Discharge from Cervix",
            //     "Cervix Friable (Fragile)",
            //     "Size of the Uterus",
            //     "Position of Uterus",
            //     "Treatment Provided",
            //     "Partner's treatment",
            //     "Treatment",
            //     "Name",
            //     "LCC",
            //     "Systematic Examination",
            //     "Diagnosis",
            //     "Suggestions/Advice",
            //     "First Aid",
            //     "Type of Injury",
            //     "Treatment Needed",
            //     "TB",
            //     "BCG Vaccines Taken?",
            //     "Investigation Order:",
            //     "TB Diagnosis",
            //     "Treatment for DOTs",
            //     "TB History/signs (select if present)",
            //     "Eye Care",
            //     "Local Examination",
            //     "Cornea",
            //     "Outward Referral",
            //     "CLIENT INFORMATION",
            //     "Referred to",
            //     "Provisional Diagnosis",
            //     "Chief Complains",
            //     "Reason for Referral",
            //     "History of allergy",
            //     "Medication",
            //     "Past medical history",
            //     "Last Meal",
            //     "Events",
            //     "Airway",
            //     "Breathing",
            //     "Circulation",
            //     "Conscious",
            //     "Exposure"
            // ];


            $scope.checkObsCondition = function (observation) {
                var metaDate =  $rootScope.fetchedPrescribedData;
                if ($rootScope.isBeingPrinted) {
                    var flag = metaDate.indexOf(observation);
                    if (flag !== -1) {
                        return true;
                    }
                    else return false;
                }
                else {
                    return true;
                }
            };

        };
        return {
            restrict: 'E',
            scope: {
                observation: "=?",
                patient: "=",
                showDate: "=?",
                showTime: "=?",
                showDetailsButton: "=?"
            },
            controller: controller,
            template: '<ng-include src="\'../common/obs/views/showObservation.html\'" />'
        };
    }]);
